version: '3'

services:
  mysql:
    image: mysql:8.0.26
    tmpfs: /var/lib/mysql:rw
    command:
      --default-time-zone=+8:00
      --innodb-buffer-pool-size=20M
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_DATABASE=example_db"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"

#  zookeeper:
#    image: confluentinc/cp-zookeeper:6.2.1
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 22181:2181
#
#  kafka:
#    image: confluentinc/cp-kafka:6.2.1
#    depends_on:
#      - zookeeper
#    ports:
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1