spring:
  application:
    name: example-service

  profiles:
    active: local

  flyway:
    enabled: true
    locations: classpath:/db/migration
    out-of-order: true

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  config: classpath:${SPRING_CONFIG_FILE:logback-spring.xml}

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:abc!23}

gateways:
  weather:
    host: http://t.weather.itboy.net/api/weather/city/101270101
    connectTimeout: 5000
    readTimeout: 5000