# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Github Actions

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

env:
  TZ: Asia/Shanghai
  DOCKER_IMAGE_URL: docker.io/amuguelove/example-service

jobs:
  build:
    name: Build & Publish artifact
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.26
        env:
          MYSQL_DATABASE: example_db
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      redis:
        image: redis:6.2.5
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 6379:6379

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: joschi/setup-jdk@v2
      with:
        java-version: '11' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'

    - name: Cache gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with gradle
      run: ./gradlew clean build -PALIYUN_MAVEN_USER=${{ secrets.ALIYUN_MAVEN_USER}} -PALIYUN_MAVEN_PASSWORD=${{ secrets.ALIYUN_MAVEN_PASSWORD}}

    - name: Set image tag
      run: echo "IMAGE_TAG=$(date +'%Y-%m-%d-%H%M%S')-${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Container build and push to Docker Registry
      run: |
        docker login -u ${{ secrets.DOCKER_REGISTRY_ACCOUNT }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        docker build -t ${DOCKER_IMAGE_URL}:${IMAGE_TAG} .
        docker push ${DOCKER_IMAGE_URL}:${IMAGE_TAG}

  helm-deploy:
    name: Helm lint & deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Helm Lint
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm lint ./charts/example-service

    - name: Helm deploy to dev
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm upgrade --install example-service ./charts/example-service -n dev --set spring.profile=dev --set image.tag=${IMAGE_TAG}
        kubeconfig: '${{ secrets.KUBECONFIG }}'